# Generated by Django 4.2.1 on 2023-06-05 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255, verbose_name='Videos')),
                ('nome', models.CharField(default='', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='', max_length=2000, verbose_name='Descricao')),
                ('premium', models.TextField(default=False, verbose_name='Videos Premium')),
            ],
            options={
                'verbose_name': 'Perfil Incluso',
                'verbose_name_plural': 'Perfis Inclusos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(default='', max_length=255, verbose_name='Tipo de pagamento')),
                ('preco_pedido', models.FloatField(default=0, verbose_name='Preço do pedido')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('status_pedido', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20, verbose_name='Status Pedido')),
                ('recebeu_email_aprovado', models.BooleanField(default=False, verbose_name='Código Interno AP')),
                ('recebeu_email_reprovado', models.BooleanField(default=False, verbose_name='Código Interno REP')),
                ('recebeu_email_pendente', models.BooleanField(default=False, verbose_name='Código Interno PEN')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.perfil', verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
