# Generated by Django 4.2.1 on 2023-06-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videos_options_videos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_videos/%Y/%m/%d', verbose_name='Foto'),
        ),
    ]
