# Generated by Django 4.2.1 on 2023-06-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
