# Generated by Django 4.2.1 on 2023-06-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_usuario'),
        ('videos', '0004_delete_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255, verbose_name='Videos')),
                ('nome', models.CharField(default='', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='', max_length=2000, verbose_name='Descricao')),
                ('premium', models.TextField(default=False, verbose_name='Videos Premium')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_videos/%Y/%m/%d', verbose_name='Foto')),
                ('menina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.meninas', verbose_name='Menina')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
