# Generated by Django 4.2.1 on 2023-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.CharField(default='', max_length=255, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Videos Premium'),
        ),
    ]
