# Generated by Django 4.2.1 on 2023-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_videos_link_alter_videos_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='nome',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
