# Generated by Django 4.2.1 on 2023-06-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_comentarios_visibilidade_alter_comentarios_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='IdTransaction',
            field=models.IntegerField(default=0, verbose_name='IdTransaction'),
        ),
    ]
