# Generated by Django 4.2.1 on 2023-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_pedido_idtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='IdTransaction',
            field=models.IntegerField(default=0, verbose_name='IdTransaction'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descricao_pagamento',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descrição do pagamento'),
        ),
    ]
