# Generated by Django 4.2.1 on 2023-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_alter_pedido_idtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='plano',
            field=models.CharField(choices=[('tres_meses', 'tres_meses'), ('seis_meses', 'seis_meses'), ('doze_meses', 'doze_meses')], default='tres_meses', max_length=20, verbose_name='Status Pedido'),
        ),
    ]
