# Generated by Django 4.2.1 on 2023-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_pedido_plano_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tres_meses', models.IntegerField(default=0, verbose_name='Três meses')),
                ('seis_meses', models.IntegerField(default=0, verbose_name='Seis meses')),
                ('doze_meses', models.IntegerField(default=0, verbose_name='Doze meses (1 ano)')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plano_ativo',
            field=models.BooleanField(default=False, verbose_name='Plano Ativo'),
        ),
    ]
