# Generated by Django 4.2.1 on 2023-06-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_planos_alter_pedido_plano_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='doze_meses',
            field=models.FloatField(default=0, verbose_name='Doze meses (1 ano)'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='seis_meses',
            field=models.FloatField(default=0, verbose_name='Seis meses'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='tres_meses',
            field=models.FloatField(default=0, verbose_name='Três meses'),
        ),
    ]
