# Generated by Django 4.2.1 on 2023-06-26 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_pedido_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_vencimento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do vencimento'),
        ),
    ]
