# Generated by Django 4.2.1 on 2023-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_alter_pedido_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_vencimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do vencimento'),
        ),
    ]
