# Generated by Django 4.2.1 on 2023-07-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_delete_comentarios'),
        ('videos', '0022_pedido_parcelamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(default='', max_length=255, unique=True, verbose_name='Nome')),
                ('arquivo', models.FileField(upload_to='audios/%Y/%m/%d', verbose_name='Audio')),
                ('menina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.meninas', verbose_name='Menina')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
            },
        ),
    ]
