# Generated by Django 4.2.1 on 2023-07-03 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_delete_comentarios'),
        ('videos', '0024_alter_audios_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVideoPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tipo de pagamento')),
                ('preco_pedido', models.FloatField(default=0, verbose_name='Preço do pedido')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('descricao_pagamento', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descrição do pagamento')),
                ('status_pedido', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20, verbose_name='Status Pedido')),
                ('IdTransaction', models.IntegerField(default=0, verbose_name='IdTransaction')),
                ('parcelamentos', models.IntegerField(default=0, verbose_name='Parcelamentos')),
                ('recebeu_email_aprovado', models.BooleanField(default=False, verbose_name='Código Interno AP')),
                ('recebeu_email_reprovado', models.BooleanField(default=False, verbose_name='Código Interno REP')),
                ('recebeu_email_pendente', models.BooleanField(default=False, verbose_name='Código Interno PEN')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.perfil', verbose_name='Comprador')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.videos', verbose_name='Video Premium')),
            ],
            options={
                'verbose_name': 'Pedido Video Premium',
                'verbose_name_plural': 'Pedidos Videos Premium',
            },
        ),
    ]
