# Generated by Django 4.2.1 on 2023-07-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_alter_pedidovideopremium_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='doze_meses',
        ),
        migrations.AddField(
            model_name='planos',
            name='um_mes',
            field=models.FloatField(default=0, verbose_name='Um mes'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plano',
            field=models.CharField(choices=[('tres_meses', 'tres_meses'), ('seis_meses', 'seis_meses'), ('um_mes', 'um_mes')], default='tres_meses', max_length=20, verbose_name='Status Pedido'),
        ),
    ]
