# Generated by Django 4.2.1 on 2023-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_remove_planos_doze_meses_planos_um_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='preco_premium',
            field=models.FloatField(default=0, verbose_name='Preço Premium'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plano',
            field=models.CharField(choices=[('tres_meses', 'tres_meses'), ('seis_meses', 'seis_meses'), ('um_mes', 'um_mes')], default='tres_meses', max_length=20, verbose_name='Plano Escolhido'),
        ),
    ]
