# Generated by Django 4.2.1 on 2023-06-18 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meninas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=255, verbose_name='Nome')),
                ('email', models.CharField(default=None, max_length=255, verbose_name='Email')),
                ('usuario', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Menina',
                'verbose_name_plural': 'Meninas',
            },
        ),
    ]
