# Generated by Django 4.2.1 on 2023-06-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
