# Generated by Django 4.2.1 on 2023-07-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_delete_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meninas',
            name='nome',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
