# Generated by Django 4.2.1 on 2023-07-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_alter_meninas_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meninas',
            name='usuario',
        ),
    ]
